Add/last commit to table
herodevs/cli pull request #63
Opened 2024-11-21 11:54 UTC by marco-ippolito

This PR adds the last commit date to the table.
Also simplifies the table creation with `console.table`.

Refs: https://github.com/orgs/neverendingsupport/projects/1/?pane=issue&itemId=87717032

2024-11-21 15:04 UTC, gkalpak requested changes

2024-11-21 15:06 UTC, marco-ippolito commented on libs/nes/init/package.json
> +    "ora": "^5.3.0"
NX was complaining about it during linting.idk why it was working before

2024-11-21 15:09 UTC, marco-ippolito commented on libs/report/committers/src/lib/get-committer-counts.ts
>        let committerCount = acc.find((c) => c.name === entry.committer);
Yeah I didn't want to refactor the current implementation 😆 but I think it can be simplified by a lot

2024-11-21 15:15 UTC, marco-ippolito commented on libs/report/committers/src/lib/get-committer-counts.ts
> +      lastCommitDates[committer] = date.toLocaleString('en-US', { timeZone: 'UTC' });
Not very human readable (I assumed this needed to be read by humand) otherwise to `.toISOString()`

2024-11-21 15:50 UTC, marco-ippolito commented on libs/nes/init/src/lib/get-product-choices.ts
>    types: ProjectType[]
Unfortunately it is used somewhere else (init.ts)

2024-11-22 17:48 UTC, gkalpak commented on libs/nes/init/package.json
> +    "ora": "^5.3.0"
Was it also complaining about the `@herodevs/*` packages? It is confusing to have them as dependencies and also use TS path mappings for them 😕

2024-11-22 18:09 UTC, gkalpak approved these changes
A couple of minor comments. Otherwise lgtm :+1:

2024-11-22 18:20 UTC, marco-ippolito commented on libs/report/committers/src/lib/print-committers.ts
I actually removed it

2024-11-22 18:24 UTC, marco-ippolito commented on libs/nes/init/package.json
> +    "ora": "^5.3.0"
Yeah if I remove it:
```diff
diff --git a/libs/nes/init/package.json b/libs/nes/init/package.json
index cb680b9..13d972a 100644
--- a/libs/nes/init/package.json
+++ b/libs/nes/init/package.json
@@ -3,7 +3,6 @@
   "version": "0.0.1",
   "dependencies": {
     "@apollo/client": "^3.10.1",
-    "@herodevs/core-types": "^0.0.1",
     "@herodevs/utility": "^0.0.1",
     "@inquirer/prompts": "^5.0.2",
     "ora": "^5.3.0",
   ```
   
The linter complains:
```

marcoippolito@marcos-MacBook-Pro cli % npm run lint

> @herodevs/source@0.0.0 lint
> nx run-many --target=lint --all
...
/Users/marcoippolito/Documents/projects/nes/cli/libs/nes/init/package.json
 4:3  error  The "init" project uses the following packages, but they are missing from "dependencies":
- @herodevs/core-types  @nx/dependency-checks
```

2024-11-22 18:40 UTC, tkwilli94 approved these changes

2024-11-22 20:32 UTC, dwelch2344 approved these changes

2024-11-22 20:33 UTC, merged